services:
  node:
    image: node:24-alpine
    volumes:
      - ./node:/app
    working_dir: /app
    command: sh -c "npm install && npm run build && npm test"

  python:
    image: python:3.10-alpine
    volumes:
      - ./python:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && rm -rf dist && rm -rf gladhost_tlds.egg-info && python -m build"
    environment:
      - PYTHONPATH=/app
